class StorageEncryption {
    constructor(key = 'sllowly_secret_key_2024') { this.key = key; }
    encrypt(data) { const jsonStr = JSON.stringify(data); let result = ''; for (let i = 0; i < jsonStr.length; i++) { const charCode = jsonStr.charCodeAt(i) ^ this.key.charCodeAt(i % this.key.length); result += String.fromCharCode(charCode); } return btoa(result); }
    decrypt(encryptedData) { try { const decoded = atob(encryptedData); let result = ''; for (let i = 0; i < decoded.length; i++) { const charCode = decoded.charCodeAt(i) ^ this.key.charCodeAt(i % this.key.length); result += String.fromCharCode(charCode); } return JSON.parse(result); } catch (e) { return null; } }
}
const storageEncryption = new StorageEncryption();
const secureStorage = { setItem: function(key, value) { const encrypted = storageEncryption.encrypt(value); localStorage.setItem(key, encrypted); }, getItem: function(key) { const encrypted = localStorage.getItem(key); if (!encrypted) return null; return storageEncryption.decrypt(encrypted); }, removeItem: function(key) { localStorage.removeItem(key); }, clear: function() { localStorage.clear(); } };
const userStorage = { saveLicense: function(license) { secureStorage.setItem(CONFIG.STORAGE_KEYS.LICENSE, license); }, getLicense: function() { return secureStorage.getItem(CONFIG.STORAGE_KEYS.LICENSE); }, saveDeviceId: function(deviceId) { secureStorage.setItem(CONFIG.STORAGE_KEYS.DEVICE_ID, deviceId); }, getDeviceId: function() { return secureStorage.getItem(CONFIG.STORAGE_KEYS.DEVICE_ID); }, saveCreatedAccounts: function(accounts) { const existing = this.getCreatedAccounts() || []; const updated = [...existing, ...accounts]; secureStorage.setItem(CONFIG.STORAGE_KEYS.CREATED_ACCOUNTS, updated); }, getCreatedAccounts: function() { return secureStorage.getItem(CONFIG.STORAGE_KEYS.CREATED_ACCOUNTS) || []; }, clearUserData: function() { secureStorage.removeItem(CONFIG.STORAGE_KEYS.LICENSE); secureStorage.removeItem(CONFIG.STORAGE_KEYS.USER_DATA); } };
setInterval(() => { console.clear(); console.log("%c🛡️ SllowlyTools v" + CONFIG.VERSION + " - Protected Environment", "color: #10b981; font-size: 14px; font-weight: bold;"); }, 5000);
document.addEventListener('contextmenu', function(e) { e.preventDefault(); return false; });
document.addEventListener('keydown', function(e) { if (e.key === 'F12' || (e.ctrlKey && e.shiftKey && e.key === 'I') || (e.ctrlKey && e.shiftKey && e.key === 'J') || (e.ctrlKey && e.key === 'U')) { e.preventDefault(); return false; } });